name: WorldDynamicsEngine
version: '0.1.8'
main: com.thatguycy.worlddynamicsengine.WorldDynamicsEngine
api-version: '1.20'
softdepend: [Towny, Vault]
authors: [thatguycy]
description: WorldDynamics Engine is a Minecraft plugin that adds dynamic policies to your world!
website: https://github.com/thatguycy/WorldDynamics-Engine
commands:
  wde:
    description: Main command for WorldDynamics Engine
    usage: /<command>
    aliases: [worlddynamics, wde, worlddynamicsengine, worldengine]
permissions:
  wde.help:
    description: Allows using the help subcommand of /wde
    default: true
  wde.org:
    default: true
  wde.army:
    default: true
  wde.government:
    default: true
  wde.human:
    default: true
  wde.vote:
    default: true
  wde.nation:
    default: true